# Generated by Django 4.2.23 on 2025-07-28 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieferant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmenname', models.CharField(max_length=255)),
                ('vorname', models.CharField(max_length=255)),
                ('nachname', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('hausnummer', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lieferanten_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mieteinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mieter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=255)),
                ('nachname', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('geburtsdatum', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mieter_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mietobjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strasse_hausnummer', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('kaufdatum', models.DateField()),
                ('kaufpreis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('darlehen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grundschuld', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farbe', models.CharField(choices=[('rot', 'Rot'), ('blau', 'Blau'), ('gruen', 'Grün'), ('gelb', 'Gelb'), ('schwarz', 'Schwarz')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mietobjekte_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rechnungsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechnungsarten_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('rechnungsnummer', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bezahlt_am', models.DateField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kostenpruefung_mietobjekte_app.rechnungsart')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen_created', to=settings.AUTH_USER_MODEL)),
                ('lieferant', models.ManyToManyField(to='kostenpruefung_mietobjekte_app.lieferant')),
                ('mietobjekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen', to='kostenpruefung_mietobjekte_app.mietobjekt')),
            ],
        ),
        migrations.CreateModel(
            name='Prozent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prozent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mieteinheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prozent_mieteinheit', to='kostenpruefung_mietobjekte_app.mieteinheit')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prozent_rechnung', to='kostenpruefung_mietobjekte_app.rechnung')),
            ],
        ),
        migrations.CreateModel(
            name='Mietverhaeltnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse_hausnummer', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('vertragsbeginn', models.DateField()),
                ('vertragsende', models.DateField()),
                ('kaltmiete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nebenkosten', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kaution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mietverhaeltnis_created', to=settings.AUTH_USER_MODEL)),
                ('mieteinheiten', models.ManyToManyField(to='kostenpruefung_mietobjekte_app.mieteinheit')),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mietverhaeltnisse', to='kostenpruefung_mietobjekte_app.mieter')),
                ('mietobjekte', models.ManyToManyField(to='kostenpruefung_mietobjekte_app.mietobjekt')),
            ],
        ),
        migrations.AddField(
            model_name='mieteinheit',
            name='mietobjekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mieteinheiten', to='kostenpruefung_mietobjekte_app.mietobjekt'),
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buchungstag', models.DateField()),
                ('kontoinhaber', models.CharField(max_length=255)),
                ('buchungstext', models.CharField(max_length=255)),
                ('betrag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('werterstellung', models.DateField()),
                ('buchungsart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kostenpruefung_mietobjekte_app.rechnungsart')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konto_created', to=settings.AUTH_USER_MODEL)),
                ('lieferanten', models.ManyToManyField(to='kostenpruefung_mietobjekte_app.lieferant')),
                ('mieter', models.ManyToManyField(blank=True, to='kostenpruefung_mietobjekte_app.mieter')),
                ('mietobjekt', models.ManyToManyField(to='kostenpruefung_mietobjekte_app.mietobjekt')),
            ],
        ),
        migrations.CreateModel(
            name='Buchungsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buchungsart_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
