# Generated by Django 4.2.23 on 2025-07-25 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kostenpruefung_mietobjekte_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buchungstag', models.DateField()),
                ('kontoinhaber', models.CharField(max_length=255)),
                ('buchungstext', models.CharField(max_length=255)),
                ('werterstellung', models.DateField()),
                ('buchungsart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kostenpruefung_mietobjekte_app.rechnungsart')),
                ('lieferanten', models.ManyToManyField(to='kostenpruefung_mietobjekte_app.lieferant')),
                ('mieter', models.ManyToManyField(to='kostenpruefung_mietobjekte_app.mieter')),
            ],
        ),
        migrations.CreateModel(
            name='Buchungsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buchungsart_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
