# Generated by Django 4.2.23 on 2025-08-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnungsart',
            name='farbe',
            field=models.CharField(default='#4e79a7', help_text='Farbe für Diagramme (Hex-Code, z.B. #FF5733)', max_length=7),
        ),
    ]
