# Generated by Django 4.2.23 on 2025-07-25 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kostenpruefung_mietobjekte_app', '0002_konto_buchungsart'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konto_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
