# Generated by Django 4.2.23 on 2025-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0002_rechnungsart_farbe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mietobjekt',
            name='darlehen',
        ),
        migrations.RemoveField(
            model_name='mietobjekt',
            name='grundschuld',
        ),
        migrations.RemoveField(
            model_name='mietobjekt',
            name='kaufdatum',
        ),
        migrations.RemoveField(
            model_name='mietobjekt',
            name='kaufpreis',
        ),
        migrations.AddField(
            model_name='mieteinheit',
            name='darlehen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mieteinheit',
            name='grundschuld',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mieteinheit',
            name='kaufdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mieteinheit',
            name='kaufpreis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
