# Generated by Django 4.2.23 on 2025-08-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0003_remove_mietobjekt_darlehen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietverhaeltnis',
            name='vertragsende',
            field=models.DateField(blank=True, null=True),
        ),
    ]
