# Generated by Django 4.2.23 on 2025-07-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0003_konto_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mieteinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mieteinheiten', to='kostenpruefung_mietobjekte_app.mietobjekt')),
            ],
        ),
        migrations.RemoveField(
            model_name='rechnung',
            name='mietobjekte',
        ),
        migrations.AddField(
            model_name='rechnung',
            name='mietobjekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen', to='kostenpruefung_mietobjekte_app.mietobjekt'),
        ),
        migrations.CreateModel(
            name='Prozent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prozent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mieteinheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prozent_mieteinheit', to='kostenpruefung_mietobjekte_app.mieteinheit')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prozent_rechnung', to='kostenpruefung_mietobjekte_app.rechnung')),
            ],
        ),
    ]
