# Generated by Django 4.2.23 on 2025-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0004_mieteinheit_remove_rechnung_mietobjekte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prozent',
            name='prozent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
