# Generated by Django 4.2.23 on 2025-07-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0006_mieter_mieteinheiten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mieter',
            name='mieteinheiten',
            field=models.ManyToManyField(to='kostenpruefung_mietobjekte_app.mieteinheit'),
        ),
    ]
