# Generated by Django 4.2.23 on 2025-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0007_alter_mieter_mieteinheiten'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='mietobjekt',
            field=models.ManyToManyField(to='kostenpruefung_mietobjekte_app.mietobjekt'),
        ),
    ]
