# Generated by Django 4.2.23 on 2025-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0008_konto_mietobjekt'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='betrag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
