# Generated by Django 4.2.23 on 2025-07-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kostenpruefung_mietobjekte_app', '0009_konto_betrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='mieter',
            field=models.ManyToManyField(blank=True, null=True, to='kostenpruefung_mietobjekte_app.mieter'),
        ),
    ]
